# Generated by Django 4.0 on 2021-12-10 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('achievement_date', models.DateField()),
                ('academic_year', models.PositiveSmallIntegerField()),
                ('certificate', models.FileField(upload_to='')),
                (
                'organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.organization')),
            ],
        ),
    ]
