# Generated by Django 4.0 on 2021-12-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
