# Generated by Django 4.0 on 2021-12-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_achievement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='certificate',
            field=models.FileField(upload_to='ucertificates/'),
        ),
    ]
